#ifndef __MDM_OBJECTID_H__
#define __MDM_OBJECTID_H__


/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


/*!\file mdm_objectid.h 
 * \brief Automatically generated header file mdm_objectid.h
 */


/*! \brief InternetGatewayDevice. */
#define MDMOID_IGD  1

/*! \brief InternetGatewayDevice.X_TPLINK_TrafficControl. */
#define MDMOID_TC  2

/*! \brief InternetGatewayDevice.X_TPLINK_TrafficControl.TCRule.{i}. */
#define MDMOID_TC_RULE  3

/*! \brief InternetGatewayDevice.DeviceInfo. */
#define MDMOID_IGD_DEVICE_INFO  4

/*! \brief InternetGatewayDevice.DeviceInfo.VendorConfigFile.{i}. */
#define MDMOID_VENDOR_CONFIG_FILE  5

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_BpaApiFlowHandle.{i}. */
#define MDMOID_BPA_API_FLOW_HANDLE  6

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_SyslogCfg. */
#define MDMOID_SYSLOG_CFG  7

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_LoginCfg. */
#define MDMOID_LOGIN_CFG  8

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg. */
#define MDMOID_APP_CFG  9

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.HttpdCfg. */
#define MDMOID_HTTPD_CFG  10

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.Tr69cCfg. */
#define MDMOID_TR69C_CFG  11

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.Tr64cCfg. */
#define MDMOID_TR64C_CFG  12

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.SshdCfg. */
#define MDMOID_SSHD_CFG  13

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.TelnetdCfg. */
#define MDMOID_TELNETD_CFG  14

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.ConsoledCfg. */
#define MDMOID_CONSOLED_CFG  15

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.SmdCfg. */
#define MDMOID_SMD_CFG  16

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.SskCfg. */
#define MDMOID_SSK_CFG  17

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.SnmpdCfg. */
#define MDMOID_SNMPD_CFG  18

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.FtpdCfg. */
#define MDMOID_FTPD_CFG  19

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.TftpdCfg. */
#define MDMOID_TFTPD_CFG  20

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.PppdCfg. */
#define MDMOID_PPPD_CFG  21

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.IcmpCfg. */
#define MDMOID_ICMP_CFG  22

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.UpnpCfg. */
#define MDMOID_UPNP_CFG  23

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.DnsProxyCfg. */
#define MDMOID_DNS_PROXY_CFG  24

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.DectdCfg. */
#define MDMOID_DECTD_CFG  25

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.VectoringCfg. */
#define MDMOID_VECTORING_CFG  26

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.OmcidCfg. */
#define MDMOID_OMCID_CFG  27

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.OmciPmdCfg. */
#define MDMOID_OMCI_PMD_CFG  28

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.OsgidCfg. */
#define MDMOID_OSGID_CFG  29

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_EthernetSwitch. */
#define MDMOID_ETHERNET_SWITCH  30

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_PwrMngtCfg. */
#define MDMOID_PWR_MNGT  31

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_StandbyCfg. */
#define MDMOID_STANDBY_CFG  32

/*! \brief InternetGatewayDevice.DeviceConfig. */
#define MDMOID_DEVICE_CONFIG  33

/*! \brief InternetGatewayDevice.ManagementServer. */
#define MDMOID_MANAGEMENT_SERVER  34

/*! \brief InternetGatewayDevice.ManagementServer.ManageableDevice.{i}. */
#define MDMOID_MANAGEABLE_DEVICE  35

/*! \brief InternetGatewayDevice.Time. */
#define MDMOID_TIME_SERVER_CFG  36

/*! \brief InternetGatewayDevice.Layer2Bridging. */
#define MDMOID_L2_BRIDGING  37

/*! \brief InternetGatewayDevice.Layer2Bridging.Bridge.{i}. */
#define MDMOID_L2_BRIDGING_ENTRY  38

/*! \brief InternetGatewayDevice.Layer2Bridging.Filter.{i}. */
#define MDMOID_L2_BRIDGING_FILTER  39

/*! \brief InternetGatewayDevice.Layer2Bridging.AvailableInterface.{i}. */
#define MDMOID_L2_BRIDGING_INTF  40

/*! \brief InternetGatewayDevice.QueueManagement. */
#define MDMOID_Q_MGMT  41

/*! \brief InternetGatewayDevice.QueueManagement.Classification.{i}. */
#define MDMOID_Q_MGMT_CLASSIFICATION  42

/*! \brief InternetGatewayDevice.QueueManagement.Policer.{i}. */
#define MDMOID_Q_MGMT_POLICER  43

/*! \brief InternetGatewayDevice.QueueManagement.Queue.{i}. */
#define MDMOID_Q_MGMT_QUEUE  44

/*! \brief InternetGatewayDevice.IPPingDiagnostics. */
#define MDMOID_IP_PING_DIAG  45

/*! \brief InternetGatewayDevice.EponSoftwareImage.{i}. */
#define MDMOID_EPON_SOFTWARE_IMAGE  46

/*! \brief InternetGatewayDevice.EponSwUpgradeStatus. */
#define MDMOID_EPON_SW_UPGRADE_STATUS  47

/*! \brief InternetGatewayDevice.LANDevice.{i}. */
#define MDMOID_LAN_DEV  48

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IgmpSnoopingConfig. */
#define MDMOID_IGMP_SNOOPING_CFG  49

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement. */
#define MDMOID_LAN_HOST_CFG  50

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}. */
#define MDMOID_LAN_IP_INTF  51

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_BROADCOM_COM_IPv6LanIntfAddress. */
#define MDMOID_I_PV6_LAN_INTF_ADDR  52

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_BROADCOM_COM_IPv6LanIntfAddress.DelegatedAddress.{i}. */
#define MDMOID_DELEGATED_ADDRESS  53

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_BROADCOM_COM_FirewallException.{i}. */
#define MDMOID_LAN_IP_INTF_FIREWALL_EXCEPTION  54

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_BROADCOM_COM_IpFilterCfg.{i}. */
#define MDMOID_IP_FILTER_CFG  55

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}. */
#define MDMOID_DHCP_CONDITIONAL_SERVING  56

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IPv6LANHostConfigManagement. */
#define MDMOID_I_PV6_LAN_HOST_CFG  57

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IPv6LANHostConfigManagement.RadvdConfigManagement. */
#define MDMOID_RADVD_CONFIG_MGT  58

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IPv6LANHostConfigManagement.RadvdConfigManagement.ULAPrefixInfo. */
#define MDMOID_ULA_PREFIX_INFO  59

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IPv6LANHostConfigManagement.RadvdConfigManagement.PrefixInformation.{i}. */
#define MDMOID_PREFIX_INFO  60

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IPv6LANHostConfigManagement.X_BROADCOM_COM_MldSnoopingConfig. */
#define MDMOID_MLD_SNOOPING_CFG  61

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}. */
#define MDMOID_LAN_ETH_INTF  62

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_ETH_INTF_STATS  63

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}. */
#define MDMOID_LAN_USB_INTF  64

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_USB_INTF_STATS  65

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}. */
#define MDMOID_LAN_WLAN  66

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.AssociatedDevice.{i}. */
#define MDMOID_LAN_WLAN_ASSOCIATED_DEVICE_ENTRY  67

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WEPKey.{i}. */
#define MDMOID_LAN_WLAN_WEP_KEY  68

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.PreSharedKey.{i}. */
#define MDMOID_LAN_WLAN_PRE_SHARED_KEY  69

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter. */
#define MDMOID_WLAN_ADAPTER  70

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlBaseCfg. */
#define MDMOID_WL_BASE_CFG  71

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlStaticWdsCfg.{i}. */
#define MDMOID_WL_STATIC_WDS_CFG  72

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlWdsCfg.{i}. */
#define MDMOID_WL_WDS_CFG  73

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlScanWdsCfg.{i}. */
#define MDMOID_WL_SCAN_WDS_CFG  74

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlMimoCfg. */
#define MDMOID_WL_MIMO_CFG  75

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlSesCfg. */
#define MDMOID_WL_SES_CFG  76

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlVirtIntfCfg.{i}. */
#define MDMOID_WL_VIRT_INTF_CFG  77

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlVirtIntfCfg.{i}.WlMacFltCfg.{i}. */
#define MDMOID_WL_MAC_FLT  78

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlVirtIntfCfg.{i}.WlKey64Cfg.{i}. */
#define MDMOID_WL_KEY64_CFG  79

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlVirtIntfCfg.{i}.WlKey128Cfg.{i}. */
#define MDMOID_WL_KEY128_CFG  80

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlVirtIntfCfg.{i}.WlWpsCfg. */
#define MDMOID_WL_WPS_CFG  81

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.TaskSchedule. */
#define MDMOID_WL_SCHEDULE  82

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.GuestNetwork. */
#define MDMOID_WL_GUEST_NWK  83

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WLANVirtMbssConfiguration.{i}. */
#define MDMOID_LAN_WLAN_VIRT_MBSS  84

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANMocaInterfaceConfig.{i}. */
#define MDMOID_LAN_MOCA_INTF  85

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANMocaInterfaceConfig.{i}.Status. */
#define MDMOID_LAN_MOCA_INTF_STATUS  86

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANMocaInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_MOCA_INTF_STATS  87

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANEponInterfaceConfig.{i}. */
#define MDMOID_LAN_EPON_INTF  88

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANEponInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_EPON_INTF_STATS  89

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts. */
#define MDMOID_LAN_HOSTS  90

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts.Host.{i}. */
#define MDMOID_LAN_HOST_ENTRY  91

/*! \brief InternetGatewayDevice.WANDevice.{i}. */
#define MDMOID_WAN_DEV  92

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANCommonInterfaceConfig. */
#define MDMOID_WAN_COMMON_INTF_CFG  93

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_XTM_Interface_Stats.{i}. */
#define MDMOID_XTM_INTERFACE_STATS  94

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig. */
#define MDMOID_WAN_DSL_INTF_CFG  95

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.X_BROADCOM_COM_BertTest. */
#define MDMOID_WAN_BERT_TEST  96

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats. */
#define MDMOID_WAN_DSL_INTF_STATS  97

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Total. */
#define MDMOID_WAN_DSL_INTF_STATS_TOTAL  98

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Showtime. */
#define MDMOID_WAN_DSL_INTF_STATS_SHOWTIME  99

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.CurrentDay. */
#define MDMOID_WAN_DSL_INTF_STATS_CURRENT_DAY  100

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.QuarterHour. */
#define MDMOID_WAN_DSL_INTF_STATS_QUARTER_HOUR  101

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.TestParams. */
#define MDMOID_WAN_DSL_TEST_PARAMS  102

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig. */
#define MDMOID_WAN_ETH_INTF  103

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.X_BROADCOM_COM_IPv6Address.{i}. */
#define MDMOID_I_PV6_ADDR  104

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.Stats. */
#define MDMOID_WAN_ETH_INTF_STATS  105

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANMocaInterfaceConfig. */
#define MDMOID_WAN_MOCA_INTF  106

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANMocaInterfaceConfig.Status. */
#define MDMOID_WAN_MOCA_INTF_STATUS  107

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANMocaInterfaceConfig.Stats. */
#define MDMOID_WAN_MOCA_INTF_STATS  108

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_EponInterfaceConfig. */
#define MDMOID_WAN_EPON_INTF  109

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_EponInterfaceConfig.Stats. */
#define MDMOID_WAN_EPON_INTF_STATS  110

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_L2tpAcIntfConfig. */
#define MDMOID_L2TP_AC_INTF_CONFIG  111

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANPonInterfaceConfig. */
#define MDMOID_WAN_PON_INTF  112

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANPonInterfaceConfig.Stats. */
#define MDMOID_WAN_PON_INTF_STATUS  113

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLDiagnostics. */
#define MDMOID_WAN_DSL_DIAG  114

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANDSLDiagnostics. */
#define MDMOID_WAN_DSL_PROPRIETARY_DIAG  115

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANDSLDiagnostics.PeakLineNoise. */
#define MDMOID_WAN_DSL_DIAG_PLN  116

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANDSLDiagnostics.NonLinearity. */
#define MDMOID_WAN_DSL_DIAG_NON_LINEARITY  117

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}. */
#define MDMOID_WAN_CONN_DEVICE  118

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANATMF4EndToEndLoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F4_END_TO_END_LOOPBACK_DIAG  119

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANATMF4LoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F4_LOOPBACK_DIAG  120

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANATMF5EndToEndLoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F5_END_TO_END_LOOPBACK_DIAG  121

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANGPONLinkConfig. */
#define MDMOID_WAN_GPON_LINK_CFG  122

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANEPONLinkConfig. */
#define MDMOID_WAN_EPON_LINK_CFG  123

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig. */
#define MDMOID_WAN_DSL_LINK_CFG  124

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig.X_BROADCOM_COM_ATM_PARMS. */
#define MDMOID_WAN_DSL_ATM_PARAMS  125

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANATMF5LoopbackDiagnostics. */
#define MDMOID_WAN_ATM5_LOOPBACK_DIAG  126

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPTMLinkConfig. */
#define MDMOID_WAN_PTM_LINK_CFG  127

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANEthernetLinkConfig. */
#define MDMOID_WAN_ETH_LINK_CFG  128

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_L2tpAcLinkConfig. */
#define MDMOID_L2TP_AC_LINK_CONFIG  129

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANUSB3GLinkConfig. */
#define MDMOID_WAN_USB3G_LINK_CFG  130

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANUSB3GLinkConfig.UsbModemParam.{i}. */
#define MDMOID_USB_MODEM_PARAM  131

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}. */
#define MDMOID_WAN_IP_CONN  132

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.PortMapping.{i}. */
#define MDMOID_WAN_IP_CONN_PORTMAPPING  133

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_BROADCOM_COM_PortTriggering.{i}. */
#define MDMOID_WAN_IP_CONN_PORT_TRIGGERING  134

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_BROADCOM_COM_FirewallException.{i}. */
#define MDMOID_WAN_IP_CONN_FIREWALL_EXCEPTION  135

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_BROADCOM_COM_MacFilterObj. */
#define MDMOID_MAC_FILTER  136

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_BROADCOM_COM_MacFilterObj.X_BROADCOM_COM_MacFilterCfg.{i}. */
#define MDMOID_MAC_FILTER_CFG  137

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.Stats. */
#define MDMOID_WAN_IP_CONN_STATS  138

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}. */
#define MDMOID_WAN_PPP_CONN  139

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.PortMapping.{i}. */
#define MDMOID_WAN_PPP_CONN_PORTMAPPING  140

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_BROADCOM_COM_PortTriggering.{i}. */
#define MDMOID_WAN_PPP_CONN_PORT_TRIGGERING  141

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_BROADCOM_COM_FirewallException.{i}. */
#define MDMOID_WAN_PPP_CONN_FIREWALL_EXCEPTION  142

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.Stats. */
#define MDMOID_WAN_PPP_CONN_STATS  143

/*! \brief InternetGatewayDevice.Layer3Forwarding. */
#define MDMOID_L3_FORWARDING  144

/*! \brief InternetGatewayDevice.Layer3Forwarding.Forwarding.{i}. */
#define MDMOID_L3_FORWARDING_ENTRY  145

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPv6Layer3Forwarding. */
#define MDMOID_I_PV6_L3_FORWARDING  146

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPv6Layer3Forwarding.IPv6Forwarding.{i}. */
#define MDMOID_I_PV6_L3_FORWARDING_ENTRY  147

/*! \brief InternetGatewayDevice.Services. */
#define MDMOID_SERVICES  148

/*! \brief InternetGatewayDevice.Services.StorageService.{i}. */
#define MDMOID_STORAGE_SERVICE  149

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.UserAccount.{i}. */
#define MDMOID_USER_ACCOUNT  150

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.Capabilites. */
#define MDMOID_CAPABILITES  151

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.PhysicalMedium.{i}. */
#define MDMOID_PHYSICAL_MEDIUM  152

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.LogicalVolume.{i}. */
#define MDMOID_LOGICAL_VOLUME  153

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.SambaService. */
#define MDMOID_SAMBA_SERVICE  154

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.SMBService.SambaFolder.{i}. */
#define MDMOID_SAMBA_FOLDER  155

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.SMBService.SMB_FOLDER.{i}.SambaUserAccess.{i}. */
#define MDMOID_SAMBA_USER_ACCESS  156

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.FtpServer. */
#define MDMOID_FTP_SERVER  157

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.FTPServer.FtpFolder.{i}. */
#define MDMOID_FTP_FOLDER  158

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.FTPServer.FTPFolder.{i}.FtpUserAccess.{i}. */
#define MDMOID_FTP_USER_ACCESS  159

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.DLNA. */
#define MDMOID_DLNA  160

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.DLNA.DlnaFolder.{i}. */
#define MDMOID_DLNA_FOLDER  161

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.X_TPLINK_PrintService. */
#define MDMOID_PRINT_SERVICE  162

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}. */
#define MDMOID_VOICE  163

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}. */
#define MDMOID_VOICE_CALL_LIST  164

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.NewFlag. */
#define MDMOID_VOICE_CALL_NEW_FLAG  165

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.NumberOfMissedCalls. */
#define MDMOID_VOICE_CALL_NUMBER_OF_MISSED_CALLS  166

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.Number. */
#define MDMOID_VOICE_CALL_NUMBER  167

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.Name. */
#define MDMOID_VOICE_CALL_NAME  168

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.DateTime. */
#define MDMOID_VOICE_CALL_DATE_TIME  169

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.LineName. */
#define MDMOID_VOICE_CALL_LINE_NAME  170

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.LineId. */
#define MDMOID_VOICE_CALL_LINE_ID  171

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Call.{i}.CallType. */
#define MDMOID_VOICE_CALL_TYPE  172

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_InternalName.{i}. */
#define MDMOID_VOICE_INTERNAL_NAME_LIST  173

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_InternalName.{i}.TerminalNumber. */
#define MDMOID_VOICE_TERMINAL_NUMBER  174

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_InternalName.{i}.Name. */
#define MDMOID_VOICE_INTERNAL_NAME  175

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Contact.{i}. */
#define MDMOID_VOICE_CONTACT_LIST  176

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Contact.{i}.Name. */
#define MDMOID_VOICE_CONTACT_NAME  177

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Contact.{i}.FirstName. */
#define MDMOID_VOICE_CONTACT_FIRST_NAME  178

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Contact.{i}.ContactNumber. */
#define MDMOID_VOICE_CONTACT_NUMBER  179

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Contact.{i}.Melody. */
#define MDMOID_VOICE_CONTACT_MELODY  180

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Contact.{i}.LineId. */
#define MDMOID_VOICE_CONTACT_LINE_ID  181

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_SupportList.{i}. */
#define MDMOID_VOICE_DECT_SUPPORT_LIST  182

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities. */
#define MDMOID_VOICE_CAP  183

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.SIP. */
#define MDMOID_VOICE_CAP_SIP  184

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.MGCP. */
#define MDMOID_VOICE_CAP_MGCP  185

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.Codecs.{i}. */
#define MDMOID_VOICE_CAP_CODECS  186

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}. */
#define MDMOID_VOICE_PROF  187

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.ServiceProviderInfo. */
#define MDMOID_VOICE_PROF_PROVIDER  188

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.SIP. */
#define MDMOID_VOICE_PROF_SIP  189

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.SIP.EventSubscribe.{i}. */
#define MDMOID_VOICE_PROF_SIP_SUBSCRIBE  190

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.MGCP. */
#define MDMOID_VOICE_PROF_MGCP  191

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.RTP. */
#define MDMOID_VOICE_PROF_RTP  192

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.RTP.SRTP. */
#define MDMOID_VOICE_PROF_RTP_SRTP  193

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.FaxT38. */
#define MDMOID_VOICE_PROF_FAX_T38  194

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}. */
#define MDMOID_VOICE_LINE  195

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.SIP. */
#define MDMOID_VOICE_LINE_SIP  196

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.CallingFeatures. */
#define MDMOID_VOICE_LINE_CALLING_FEATURES  197

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.VoiceProcessing. */
#define MDMOID_VOICE_LINE_PROCESSING  198

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec. */
#define MDMOID_VOICE_LINE_CODEC  199

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec.List.{i}. */
#define MDMOID_VOICE_LINE_CODEC_LIST  200

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Stats. */
#define MDMOID_VOICE_LINE_STATS  201

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_LineSetting. */
#define MDMOID_VOICE_LINE_SETTING  202

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.LineName. */
#define MDMOID_VOICE_LINE_NAME  203

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.LineId. */
#define MDMOID_VOICE_LINE_DECT_LINE_ID  204

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.AttachedHandset. */
#define MDMOID_VOICE_LINE_ATTACHED_HANDSET  205

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.Melody. */
#define MDMOID_VOICE_LINE_MELODY  206

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.DialingPrefix. */
#define MDMOID_VOICE_LINE_DIALING_PREFIX  207

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.Volumn. */
#define MDMOID_VOICE_LINE_VOLUMN  208

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.BlockedNumber. */
#define MDMOID_VOICE_LINE_BLOCKED_NUMBER  209

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.MultiCallMode. */
#define MDMOID_VOICE_LINE_MULTI_CALL_MODE  210

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.IntrusionCall. */
#define MDMOID_VOICE_LINE_INTRUSION_CALL  211

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.CLIR. */
#define MDMOID_CLI_R  212

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_BROADCOM_COM_DectLineSetting.CallForwarding. */
#define MDMOID_VOICE_LINE_CALL_FORWARDING  213

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.PhyInterface.{i}. */
#define MDMOID_VOICE_PHY_INTF  214

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.PhyInterface.{i}.Tests. */
#define MDMOID_VOICE_PHY_INTF_TESTS  215

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_PSTN.{i}. */
#define MDMOID_VOICE_PSTN  216

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Ntr. */
#define MDMOID_VOICE_NTR  217

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_BROADCOM_COM_Ntr.History.{i}. */
#define MDMOID_VOICE_NTR_HISTORY  218

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface. */
#define MDMOID_VOICE_DECT_SYSTEM_SETTING  219

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.Handset.{i}. */
#define MDMOID_DECT_HANDSET  220

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.PINCode. */
#define MDMOID_VOICE_DECT_PIN_CODE  221

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.ClockMaster. */
#define MDMOID_VOICE_DECT_CLOCK_MASTER  222

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.ResetBase. */
#define MDMOID_VOICE_DECT_RESET_BASE  223

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.FirmwareVersion. */
#define MDMOID_VOICE_DECT_FIRMWARE_VERSION  224

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.HardwareVersion. */
#define MDMOID_VOICE_DECT_HARDWARE_VERSION  225

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.EEPROMVersion. */
#define MDMOID_EEPROM_VERSION  226

/*! \brief InternetGatewayDevice.X_TP_IPTV. */
#define MDMOID_IPTV  227

/*! \brief InternetGatewayDevice.X_TP_IPTV.DslIptvCfg. */
#define MDMOID_DSL_IPTV_CFG  228

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_SnmpCfg. */
#define MDMOID_SNMP_CFG  229

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_SecDmzHostCfg. */
#define MDMOID_SEC_DMZ_HOST_CFG  230

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AccessTimeRestriction.{i}. */
#define MDMOID_ACCESS_TIME_RESTRICTION  231

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_UrlFilterCfg. */
#define MDMOID_URL_FILTER_CFG  232

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_UrlFilterCfg.X_BROADCOM_COM_UrlFilterListCfgObj.{i}. */
#define MDMOID_URL_FILTER_LIST  233

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_DDnsCfg.{i}. */
#define MDMOID_D_DNS_CFG  234

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPPCfg. */
#define MDMOID_IPP_CFG  235

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_DebugPortMirroringCfg.{i}. */
#define MDMOID_WAN_DEBUG_PORT_MIRRORING_CFG  236

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPSecCfg.{i}. */
#define MDMOID_IP_SEC_CFG  237

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_CertificateCfg.{i}. */
#define MDMOID_CERTIFICATE_CFG  238

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_WapiCertificate. */
#define MDMOID_WAPI_CERTIFICATE  239

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_WapiCertificate.WapiAsCertificate. */
#define MDMOID_WAPI_AS_CERTIFICATE  240

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_WapiCertificate.WapiIssuedCertificate. */
#define MDMOID_WAPI_ISSUED_CERTIFICATE  241

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_NetworkConfig. */
#define MDMOID_NETWORK_CONFIG  242

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_InterfaceControl. */
#define MDMOID_INTERFACE_CONTROL  243

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_P8021agCfg. */
#define MDMOID_P8021AG_CFG  244

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_McastCfg. */
#define MDMOID_MCAST_CFG  245

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IGMPCfg. */
#define MDMOID_IGMP_CFG  246

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_MLDCfg. */
#define MDMOID_MLD_CFG  247

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPTunnel.{i}. */
#define MDMOID_IP_TUNNEL  248

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPTunnel.{i}.V4inV6Tunnel.{i}. */
#define MDMOID_IPV4IN_IPV6_TUNNEL  249

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPTunnel.{i}.V6inV4Tunnel.{i}. */
#define MDMOID_IPV6IN_IPV4_TUNNEL  250

/*! \brief InternetGatewayDevice.X_ITU_T_ORG. */
#define MDMOID_ITU_T_ORG  251

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4. */
#define MDMOID_G_984_4  252

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement. */
#define MDMOID_EQUIPMENT_MANAGEMENT  253

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.OntG. */
#define MDMOID_ONT_G  254

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.Ont2G. */
#define MDMOID_ONT2_G  255

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.OntData. */
#define MDMOID_ONT_DATA  256

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.SoftwareImage.{i}. */
#define MDMOID_SOFTWARE_IMAGE  257

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.CardHolder.{i}. */
#define MDMOID_CARD_HOLDER  258

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.CircuitPack.{i}. */
#define MDMOID_CIRCUIT_PACK  259

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.PowerShedding.{i}. */
#define MDMOID_POWER_SHEDDING  260

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.PortMappingPackageG.{i}. */
#define MDMOID_PORT_MAPPING_PACKAGE_G  261

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement. */
#define MDMOID_ANI_MANAGEMENT  262

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.AniG.{i}. */
#define MDMOID_ANI_G  263

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.TCont.{i}. */
#define MDMOID_T_CONT  264

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemPortNetworkCtp.{i}. */
#define MDMOID_GEM_PORT_NETWORK_CTP  265

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemInterworkingTp.{i}. */
#define MDMOID_GEM_INTERWORKING_TP  266

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.MulticastGemInterworkingTp.{i}. */
#define MDMOID_MULTICAST_GEM_INTERWORKING_TP  267

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.MulticastGemInterworkingTp.{i}.MulticastAddressTable.{i}. */
#define MDMOID_GEM_INTERWORKING_TP_MULTICAST_ADDRESS_TABLE  268

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemPortPmHistoryData.{i}. */
#define MDMOID_GEM_PORT_PM_HISTORY_DATA  269

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GalEthernetProfile.{i}. */
#define MDMOID_GAL_ETHERNET_PROFILE  270

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GalEthernetPmHistoryData.{i}. */
#define MDMOID_GAL_ETHERNET_PM_HISTORY_DATA  271

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.FecPmHistoryData.{i}. */
#define MDMOID_FEC_PM_HISTORY_DATA  272

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices. */
#define MDMOID_LAYER2_DATA_SERVICES  273

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgeServiceProfile.{i}. */
#define MDMOID_MAC_BRIDGE_SERVICE_PROFILE  274

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_BROADCOM_COM_MacBridgeServiceProfile.{i}. */
#define MDMOID_BC_MAC_BRIDGE_SERVICE_PROFILE  275

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgeConfigData.{i}. */
#define MDMOID_MAC_BRIDGE_CONFIG_DATA  276

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePmHistoryData.{i}. */
#define MDMOID_MAC_BRIDGE_PM_HISTORY_DATA  277

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortConfigData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_CONFIG_DATA  278

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortDesignationData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_DESIGNATION_DATA  279

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterTableData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_FILTER_TABLE_DATA  280

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterTableData.{i}.MacFilterTable.{i}. */
#define MDMOID_MAC_FILTER_TABLE  281

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterPreAssignTable.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_FILTER_PRE_ASSIGN_TABLE  282

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortBridgeTableData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_BRIDGE_TABLE_DATA  283

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortBridgeTableData.{i}.BridgeTable.{i}. */
#define MDMOID_BRIDGE_TABLE  284

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortPmHistoryData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_PM_HISTORY_DATA  285

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MapperServiceProfile.{i}. */
#define MDMOID_MAPPER_SERVICE_PROFILE  286

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_BROADCOM_COM_MapperServiceProfile.{i}. */
#define MDMOID_BC_MAPPER_SERVICE_PROFILE  287

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.VlanTaggingFilterData.{i}. */
#define MDMOID_VLAN_TAGGING_FILTER_DATA  288

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.VlanTaggingOperationConfigurationData.{i}. */
#define MDMOID_VLAN_TAGGING_OPERATION_CONFIGURATION_DATA  289

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.ExtendedVlanTaggingOperationConfigurationData.{i}. */
#define MDMOID_EXTENDED_VLAN_TAGGING_OPERATION_CONFIGURATION_DATA  290

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.ExtendedVlanTaggingOperationConfigurationData.{i}.ReceivedFrameVlanTaggingOperationTable.{i}. */
#define MDMOID_RECEIVED_FRAME_VLAN_TAGGING_OPERATION_TABLE  291

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}. */
#define MDMOID_MULTICAST_OPERATIONS_PROFILE  292

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.DynamicAccessControlListTable.{i}. */
#define MDMOID_DYNAMIC_ACCESS_CONTROL_LIST_TABLE  293

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.StaticAccessControlListTable.{i}. */
#define MDMOID_STATIC_ACCESS_CONTROL_LIST_TABLE  294

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.LostGroupsListTable.{i}. */
#define MDMOID_LOST_GROUPS_LIST_TABLE  295

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberConfigInfo.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER_CONFIG_INFO  296

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberMonitor.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER_MONITOR  297

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberMonitor.{i}.ActiveGroupsListTable.{i}. */
#define MDMOID_ACTIVE_GROUPS_LIST_TABLE  298

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_BROADCOM_COM_MulticastSubscriberMonitor.{i}. */
#define MDMOID_BC_MULTICAST_SUBSCRIBER_MONITOR  299

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_BROADCOM_COM_MulticastSubscriberMonitor.{i}.MulticastSubscriber.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER  300

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.UpstreamEthernetFramePmHistoryData.{i}. */
#define MDMOID_UPSTREAM_ETHERNET_FRAME_PM_HISTORY_DATA  301

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.DownstreamEthernetFramePmHistoryData.{i}. */
#define MDMOID_DOWNSTREAM_ETHERNET_FRAME_PM_HISTORY_DATA  302

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices. */
#define MDMOID_LAYER3_DATA_SERVICES  303

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.IpHostConfigData.{i}. */
#define MDMOID_IP_HOST_CONFIG_DATA  304

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.X_BROADCOM_COM_IpHostConfigData.{i}. */
#define MDMOID_BC_IP_HOST_CONFIG_DATA  305

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.IpHostPmHistoryData.{i}. */
#define MDMOID_IP_HOST_PM_HISTORY_DATA  306

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}. */
#define MDMOID_IPV6_HOST_CONFIG_DATA  307

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentAddressTable.{i}. */
#define MDMOID_IPV6_CURRENT_ADDRESS_TABLE  308

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentDefaultRouterTable.{i}. */
#define MDMOID_IPV6_CURRENT_DEFAULT_ROUTER_TABLE  309

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentDnsTable.{i}. */
#define MDMOID_IPV6_CURRENT_DNS_TABLE  310

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentOnlinkPrefixTable.{i}. */
#define MDMOID_IPV6_CURRENT_ONLINK_PREFIX_TABLE  311

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.X_BROADCOM_COM_Ipv6HostConfigData.{i}. */
#define MDMOID_BC_IPV6_HOST_CONFIG_DATA  312

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.TcpUdpConfigData.{i}. */
#define MDMOID_TCP_UDP_CONFIG_DATA  313

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices. */
#define MDMOID_ETHERNET_SERVICES  314

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.PptpEthernetUni.{i}. */
#define MDMOID_PPTP_ETHERNET_UNI  315

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA  316

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData2.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA2  317

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData3.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA3  318

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.VirtualEthernetInterfacePoint.{i}. */
#define MDMOID_VIRTUAL_ETHERNET_INTERFACE_POINT  319

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices. */
#define MDMOID_VOICE_SERVICES  320

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.PptpPotsUni.{i}. */
#define MDMOID_PPTP_POTS_UNI  321

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipUserData.{i}. */
#define MDMOID_SIP_USER_DATA  322

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipAgentConfigData.{i}. */
#define MDMOID_SIP_AGENT_CONFIG_DATA  323

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpVoiceCtp.{i}. */
#define MDMOID_VO_IP_VOICE_CTP  324

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpMediaProfile.{i}. */
#define MDMOID_VO_IP_MEDIA_PROFILE  325

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoiceServiceProfile.{i}. */
#define MDMOID_VOICE_SERVICE  326

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.RtpProfileData.{i}. */
#define MDMOID_RTP_PROFILE_DATA  327

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpAppServiceProfile.{i}. */
#define MDMOID_VO_IP_APP_SERVICE_PROFILE  328

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoiceFeatureAccessCodes.{i}. */
#define MDMOID_VOICE_FEATURE_ACCESS_CODES  329

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.NetworkDialPlanTable.{i}. */
#define MDMOID_NETWORK_DIAL_PLAN_TABLE  330

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.NetworkDialPlanTable.{i}.DialPlanTable.{i}. */
#define MDMOID_DIAL_PLAN_TABLE  331

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpLineStatus.{i}. */
#define MDMOID_VO_IP_LINE_STATUS  332

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.CallControlPmHistoryData.{i}. */
#define MDMOID_CALL_CONTROL_PM_HISTORY_DATA  333

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.RtpPmHistoryData.{i}. */
#define MDMOID_RTP_PM_HISTORY_DATA  334

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipAgentPmHistoryData.{i}. */
#define MDMOID_SIP_AGENT_PM_HISTORY_DATA  335

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipCallInitPmHistoryData.{i}. */
#define MDMOID_SIP_CALL_INIT_PM_HISTORY_DATA  336

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.MgcConfigData.{i}. */
#define MDMOID_MGC_CONFIG_DATA  337

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.MgcPmHistoryData.{i}. */
#define MDMOID_MGC_PM_HISTORY_DATA  338

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpConfigData.{i}. */
#define MDMOID_VO_IP_CONFIG_DATA  339

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices. */
#define MDMOID_MOCA_SERVICES  340

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.PptpMocaUni.{i}. */
#define MDMOID_PPTP_MOCA_UNI  341

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_BROADCOM_COM_PptpMocaUni.{i}. */
#define MDMOID_BRCM_PPTP_MOCA_UNI  342

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_BROADCOM_COM_MocaStatus.{i}. */
#define MDMOID_MOCA_STATUS  343

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_BROADCOM_COM_MocaStats.{i}. */
#define MDMOID_MOCA_STATS  344

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaEthernetPmHistoryData.{i}. */
#define MDMOID_MOCA_ETHERNET_PM_HISTORY_DATA  345

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaInterfacePmHistoryData.{i}. */
#define MDMOID_MOCA_INTERFACE_PM_HISTORY_DATA  346

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaInterfacePmHistoryData.{i}.NodeTable.{i}. */
#define MDMOID_MOCA_INTERFACE_PM_HISTORY_DATA_NODE_TABLE  347

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement. */
#define MDMOID_TRAFFIC_MANAGEMENT  348

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.PriorityQueueG.{i}. */
#define MDMOID_PRIORITY_QUEUE_G  349

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.TrafficSchedulerG.{i}. */
#define MDMOID_TRAFFIC_SCHEDULER_G  350

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.GemTrafficDescriptor.{i}. */
#define MDMOID_GEM_TRAFFIC_DESCRIPTOR  351

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General. */
#define MDMOID_GENERAL  352

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.UniG.{i}. */
#define MDMOID_UNI_G  353

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.OltG. */
#define MDMOID_OLT_G  354

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.NetworkAddress.{i}. */
#define MDMOID_NETWORK_ADDRESS  355

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.AuthenticationSecurityMethod.{i}. */
#define MDMOID_AUTHENTICATION_SECURITY_METHOD  356

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.LargeString.{i}. */
#define MDMOID_LARGE_STRING  357

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.ThresholdData1.{i}. */
#define MDMOID_THRESHOLD_DATA1  358

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.ThresholdData2.{i}. */
#define MDMOID_THRESHOLD_DATA2  359

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.Omci. */
#define MDMOID_OMCI  360

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.TR069ManagementServer.{i}. */
#define MDMOID_TR069_MANAGEMENT_SERVER  361

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_OmciSystem. */
#define MDMOID_OMCI_SYSTEM  362

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_GponOmciStats. */
#define MDMOID_GPON_OMCI_STATS  363

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_WlanNvram. */
#define MDMOID_WLAN_NVRAM  364

/*! \brief InternetGatewayDevice.X_CT_OAM. */
#define MDMOID_CTOAM  365

/*! \brief InternetGatewayDevice.X_CT_OAM.IADInfo. */
#define MDMOID_OAMIAD_INFO  366

/*! \brief InternetGatewayDevice.X_CT_OAM.GlobalParameterConfig. */
#define MDMOID_OAM_GLB_PARAM_CFG  367

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPParameterConfig. */
#define MDMOID_OAMSIP_PARAM_CFG  368

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPUserParameterConfig. */
#define MDMOID_OAMSIP_USR_PARAM_CFG  369

/*! \brief InternetGatewayDevice.X_CT_OAM.FAXModemConfig. */
#define MDMOID_OAMFAXMD_CFG  370

/*! \brief InternetGatewayDevice.X_CT_OAM.POTSStatus. */
#define MDMOID_OAMPOTS_STS  371

/*! \brief InternetGatewayDevice.X_CT_OAM.IADOperation. */
#define MDMOID_OAMIAD_OP  372

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPDigitMap. */
#define MDMOID_OAMSIP_DGT_MP  373

/*! \brief InternetGatewayDevice.SoftwareModules. */
#define MDMOID_SW_MODULES  374

/*! \brief InternetGatewayDevice.SoftwareModules.ExecutionUnit.{i}. */
#define MDMOID_EU  375

/*! \brief InternetGatewayDevice.SoftwareModules.ExecutionUnit.{i}.Extensions. */
#define MDMOID_EXTENSIONS  376

/*! \brief InternetGatewayDevice.SoftwareModules.ExecEnv.{i}. */
#define MDMOID_EXEC_ENV  377

/*! \brief InternetGatewayDevice.SoftwareModules.DeploymentUnit.{i}. */
#define MDMOID_DU  378

/*! \brief InternetGatewayDevice.Device. */
#define MDMOID_DEVICE  379

/*! \brief InternetGatewayDevice.Device.Optical. */
#define MDMOID_DEVICE_OPTICAL  380

/*! \brief InternetGatewayDevice.Device.Optical.Interface.{i}. */
#define MDMOID_OPTICAL_INTERFACE  381

/*! \brief InternetGatewayDevice.Device.Optical.Interface.{i}.Stats. */
#define MDMOID_OPTICAL_INTERFACE_STATS  382

/*! \brief InternetGatewayDevice.Device.HomePlug. */
#define MDMOID_DEVICE_HOME_PLUG  383

/*! \brief InternetGatewayDevice.Device.HomePlug.Interface.{i}. */
#define MDMOID_HOME_PLUG_INTERFACE  384

/*! \brief InternetGatewayDevice.Device.HomePlug.Interface.{i}.Stats. */
#define MDMOID_HOME_PLUG_INTERFACE_STATS  385

/*! \brief InternetGatewayDevice.Device.HomePlug.Interface.{i}.AssociatedDevice.{i}. */
#define MDMOID_HOME_PLUG_INTERFACE_ASSOCIATED_DEVICE  386

/*! \brief InternetGatewayDevice.X_TP_sysMode. */
#define MDMOID_SYS_MODE  387

/*! \brief maximum OID value */
#define MDM_MAX_OID 387



#endif /* __MDM_OBJECTID_H__ */
