/* this file is automatically generated, yuanshang */
#ifndef __TP_PRODUCT_H__
#define __TP_PRODUCT_H__
#define PRODUCT_MODEL "W8968"
#define PRODUCT_ID 0x08968000
#define PRODUCT_VER 3
#define SW_VER "1.0.5"
#define HW_VER "TD-W8968 V3 0x00000001"
#define PRODUCT_DESCRIPTION "300Mbps Wireless N USB ADSL2+ Modem Router"
#define CPE_ANNEX "ANNEX_A"
#define FIRMWARE_VER_PREFIX "1.0.5 Build 140212 Rel."
#define BUILD_DATE "14 02 12"
#define BUILD_TIME "14 54 57"
#endif /* __TP_PRODUCT_H__ */
