# Automatically generated by configure - do not modify!
VERSION=
PREFIX=/usr/local
prefix=$(DESTDIR)$(PREFIX)
libdir=$(DESTDIR)$(PREFIX)/lib
includedir=$(DESTDIR)$(PREFIX)/include
MAKE=make
CC=/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/bin/mips-linux-uclibc-gcc
AR=/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/bin/mips-linux-uclibc-ar
RANLIB=/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/bin/mips-linux-uclibc-ranlib
BUILD_STATIC=yes
BUILD_SHARED=no
LN=ln
STRIP=/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/bin/mips-linux-uclibc-strip
INSTALLSTRIP=-s
INSTALL=/usr/bin/install -c
DEBUG=no
